# Generated by Django 4.2.1 on 2023-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('links', models.TextField(verbose_name='Links')),
                ('published', models.DateField(verbose_name='Published')),
                ('articleRating', models.IntegerField(verbose_name='Article rating')),
                ('authorRating', models.IntegerField(verbose_name='Author rating')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('references', models.TextField(verbose_name='References')),
            ],
        ),
    ]
