# Generated by Django 4.2.1 on 2023-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='citations',
            field=models.TextField(default='', verbose_name='Citations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
