# Generated by Django 4.2.1 on 2023-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_citations_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entry_id',
            field=models.IntegerField(default=0, verbose_name='Entry_id'),
            preserve_default=False,
        ),
    ]
