# Generated by Django 4.2.1 on 2023-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entry_id',
            field=models.TextField(verbose_name='Entry_id'),
        ),
    ]
