# Generated by Django 4.2.1 on 2023-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='citations',
            field=models.JSONField(verbose_name='Citations'),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.JSONField(verbose_name='References'),
        ),
    ]
