# Generated by Django 4.2.3 on 2023-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_citations_alter_article_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.JSONField(verbose_name='Links'),
        ),
    ]
