# Generated by Django 4.2.3 on 2023-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.TextField(verbose_name='Links'),
        ),
    ]
